### ISSUE TITLE
Help Needed: CLI Syntax

### ISSUE THREAD

**Issue by KyleKing** [asmagill/mjolnir_asm.ipc#1]
Hi, I'm having trouble creating a cli tool with Mjolnir and need some help with the documentation. I want to:
1. Write a command to terminal (i.e. like the one below:  `find /Volumes -maxdepth 1 -not -user root -print0 | xargs -0 diskutil eject`)
2. Retrieve the output and create a notification (successful or not)
3. If there is an error, return the error

Could someone help me get setup and help explain the docs better? Any help would be greatly appreciated!

``` lua
mjolnir.ipc = require "mjolnir._asm.ipc" ... etc.

-- Eject All
-- Terminal Code Source: http://hints.macworld.com/article.php?story=20120901094847629
function ejectAll()
  mjolnir.ipc.handler("find /Volumes -maxdepth 1 -not -user root -print0 | xargs -0 diskutil eject")
  mjolnir.alert.show("Eject All")
end
```

**Comment by KyleKing** [comment]
@raguay Do you know how to do this?

**Comment by raguay** [comment]
@KyleKing The ipc functions are not for running command line programs, but for command line programs to talk to Mjolnir. What you want is the standard Lua command: os.execute("find /Volumes -maxdepth 1 -not -user root -print0 | xargs -0 diskutil eject"). That should work.

**Comment by asmagill** [comment]
Been away for a while... yes, @raguay is correct, the ipc module is for a command line tool, named "mjolnir" and probably installed into your /usr/local/bin directory if you installed via luarocks to the default rock tree.  If you invoke this command from the command line, you'll get a prompt and you can enter commands to Mjolnir just like you do from the application console.

Executing a shell command from within a lua script (and thus under Mjolnir control) should be done with os.exec or io.popen...  I have a version I've added at https://github.com/asmagill/hammerspoon_asm under the extras directory which is a little more useful than os.exec, as it returns the STDOUT of the command you execute, where os.exec does not... it's basically a wrapper to io.popen and the specific relevant part is pasted here:

```
--- {PATH}.{MODULE}.exec(command[, with_user_env]) -> output, status, type, rc
--- Function
--- Runs a shell command and returns stdout as a string (may include a trailing newline), followed by true or nil indicating if the command completed successfully, the exit type ("exit" or "signal"), and the result code.
---
---  If `with_user_env` is `true`, then invoke the user's default shell as an interactive login shell in which to execute the provided command in order to make sure their setup files are properly evaluated so extra path and environment variables can be set.  This is not done, if `with_user_env` is `false` or not provided, as it does add some overhead and is not always strictly necessary.
module.exec = function(command, user_env)
    local f
    if user_env then
        f = io.popen(os.getenv("SHELL").." -l -i -c \""..command.."\"", 'r')
    else
        f = io.popen(command, 'r')
    end
    local s = f:read('*a')
    local status, exit_type, rc = f:close()
    return s, status, exit_type, rc
end
```

Name it whatever you want, but now you can invoke a shell command and capture it's output for manipulation within your Mjolnir lua code.

**Comment by KyleKing** [comment]
Thanks! That answered my question perfectly!

If you don't mind me asking, I have two other questions about the environment and code:
- Can Mjolnir run any LuaRocks modules? What makes these [Mjolnir modles](https://rocks.moonscript.org/search?q=mjolnir) special?
- Can Mjolnir interact with OS X notifications like the native iMessage app to, for example, ask for a "reply" of (y/n) to begin a certain process?

![Image](http://cdn.tips-and-tricks-in-mavericks.com/images/2013/07/Reply-to-iMessage-Notifications-in-OS-X-Mavericks.png)

**Comment by raguay** [comment]
Yes, any Lua module can be used with Mjolnir. It has to be Lua 5.2 compatible. Mjolnir modules will not run on a native Lua interpreter because they make use of code that Mjolnir added to it's Lua interpreter. Therefore, using the Mjolnir name space and making use of internal calls (some of these modules are a mix of Objective C and Lua code. Especially the core modules.).

I do not know if any Lua module that has been made for working with OS X notifications. You could create the notification using AppleScript or JavaScript for Automation and run them using osascript with the os.execute() Lua command. Or, execute it in a pipe process to get the return value as in the script above.

There are Lua gui toolkits, but most of them seem to be stuck on Lua 5.1 and therefore not usable with Mjolnir.

The Mjolnir library: mjolnir._asm.ui.notification (formerly just mjolnir._asm.notification) does seem to try to handle the OS X notifications and it does have a call back function. But, I do not see how to get a value from the user. Maybe ask the author of it on how to use it. I have no experience with that module.

**Comment by asmagill** [comment]
FWIW, https://github.com/asmagill/mjolnir_asm/tree/master/_asm/compat_51 https://github.com/asmagill/mjolnir_asm/tree/master/_asm/compat_51 provides some of the lua 5.1 functionality that is missing in Mjolnir -- basically the same functions you'd get if you compiled lua 5.2 from scratch with compatibility set to ALL (it was set to none in the Mjolnir embedded version).

I haven't stress tested it yet with much, but the luarocks components themselves all work with it enabled inside of Mjolnir (at a horrible memory cost, so I abandoned that project... see https://github.com/asmagill/mjolnir_asm/tree/master/_asm https://github.com/asmagill/mjolnir_asm/tree/master/_asm if interested in reviving it)

I would suspect that it could provide a start for getting the older gui toolkits to move forward, but most of the ones I've looked at were pretty old and used a lot of stuff that's become deprecated with the last few OS X versions... I suspect it would be a big task, though this might help.

Most of the people I'm aware of do use applescript a lot for gui or interapplication communication, so I'd probably look there for starters.

## 

A-Ron

**Comment by KyleKing** [comment]
Thanks for the advice and answers!
Haha, I don't think I'm the person to revive it. Looking forward, I bet Apple will open up the API for notification interaction. Notification cards are future of mobile and desktop and there should be something for developers in iOS 9. In the meantime, I posted on superuser and will share anything I can dig up
